---
game: !ruby/hash:Sinatra::IndifferentHash
  name: Ruins of Pern
  category: Fantasy
  description: In the aftermath of a rapidly spreading virus that shattered the population,
    Ruins of Pern is set in the precarious beginning of the Third Pass. Pern's remaining
    dragonriders have consolidated in Fort Weyr due to its proximity to Hold and Hall.
    Spread far too thin between searching for survivors and keeping the land around
    Fort safe from Thread, the last remaining Weyr, Hold, and Crafthall must make
    difficult decisions on how to survive in this impossibly lonely world.
  website: https://ruins.aresmush.com/
  public_game: false
  game_status: In Development
  status: In Development
